name: Refresh Database Stocks/Cryptocurrencies

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:


jobs:
  run-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt

      - name: Run backend script
        run: |
          python -u ./backend/routes/server.py
        env: 
          GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
          REDDIT_CLIENT_ID: ${{secrets.REDDIT_CLIENT_ID}}
          REDDIT_CLIENT_SECRET: ${{secrets.REDDIT_CLIENT_SECRET}}
          REDDIT_USER_AGENT: ${{secrets.REDDIT_USER_AGENT}}
          SUPABASE_USER: ${{secrets.SUPABASE_USER}}
          SUPABASE_PASS: ${{secrets.SUPABASE_PASS}}
          SUPABASE_HOST: ${{secrets.SUPABASE_HOST}}
          SUPABASE_PORT: ${{secrets.SUPABASE_PORT}}
          SUPABASE_DB: ${{secrets.SUPABASE_DB}}
          GNEWS_API_KEY: ${{secrets.OPENAI_API_KEY}}