name: Test Database Connection

on:
  workflow_dispatch:


jobs:
  run-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      - name: Run backend script
        run: |
          python -u ./backend/test_db_connection.py
        env:
          SUPABASE_USER: ${{secrets.SUPABASE_USER}}
          SUPABASE_PASS: ${{secrets.SUPABASE_PASS}}
          SUPABASE_HOST: ${{secrets.SUPABASE_HOST}}
          SUPABASE_PORT: ${{secrets.SUPABASE_PORT}}
          SUPABASE_DB: ${{secrets.SUPABASE_DB}}
          DATABASE_URL: postgresql://${{secrets.SUPABASE_USER}}:${{secrets.SUPABASE_PASS}}@${{secrets.SUPABASE_HOST}}:${{secrets.SUPABASE_PORT}}/${{secrets.SUPABASE_DB}}